add_newline = false

format = """
[┌───────────────────>](bold green)
[│](bold green)$username$hostname$directory$git_branch$git_commit$git_state$git_status$cmd_duration$jobs
[└─>](bold green)$status$python"""
[git_branch]
format = "[$branch]($style)"
style = "bright-black"

[git_status]
format = "[[($conflicted$untracked$modified$staged$renamed$deleted)](218) ($ahead_behind$stashed)]($style)"
style = "cyan"
stashed = "≡"

[directory]
truncate_to_repo = false
truncation_length = 8
truncation_symbol = "…/"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"

[python]
format = "[$virtualenv]($style) "
style = "bright-black"

[status]
disabled = false

