# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# [character]
# Note the use of Catppuccin color 'peach'
# success_symbol = "[[󰄛](green) ❯](peach)"
# error_symbol = "[[󰄛](red) ❯](peach)"
# vimcmd_symbol = "[󰄛 ❮](subtext1)" # For use with zsh-vi-mode

# format = '$os $all'
format="""
$os \
$username\
$hostname\
${custom.sw_version}\
$directory\
$git_branch\
$git_metrics\
$git_commit\
$git_state\
$git_status\
$docker_context\
$cmd_duration\
$python\
$line_break\
$time\
$character"""

[git_metrics]
# added_style = "bg:color_aqua fg:color_fg0"
# deleted_style = "bg:color_aqua fg:color_red"
# format = """[([+$added]($added_style) )([-$deleted]($deleted_style) )](bg:color_aqua)"""
disabled = false

[git_branch]
style = "bright white"
format = '[$symbol$branch(:$remote_branch)]($style) '

[directory]
truncation_length = 4
style = "cyan"

[os]
disabled = false
style = "cyan"

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"

[time]
disabled = false
time_format = "%R"
style = "bg:color_bg1"
format = '[[$time ](fg:color_fg0 bg:color_bg1)]($style)'

[python]
format = '[${pyenv_prefix}(\($virtualenv\) )]($style)'

[cmd_duration]
format = """[[$duration](fg:yellow)]($style)"""

[line_break]
disabled = false
