# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'


# format = '$os $all'
format="""
$os \
$username\
$hostname\
${custom.sw_version}\
$directory\
$git_branch\
$git_metrics\
$git_commit\
$git_state\
$git_status\
$docker_context\
$python\
$time\
$line_break\
$cmd_duration\
$character"""

[git_metrics]
# added_style = "bg:color_aqua fg:color_fg0"
# deleted_style = "bg:color_aqua fg:color_red"
# format = """[([+$added]($added_style) )([-$deleted]($deleted_style) )](bg:color_aqua)"""
disabled = false

[git_branch]
format = '[$symbol$branch(:$remote_branch)]($style) '

[directory]
truncate_to_repo = false
style = "cyan"

[os]
disabled = false
style = "cyan"

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"

[time]
disabled = false
time_format = "%R"
style = 'bg:white fg:black'
format = '[[](fg:white)${time}[](fg:white)]($style) '

[python]
format = '[${pyenv_prefix}(\($virtualenv\) )]($style)'

[cmd_duration]
format = """[[$duration ](fg:yellow)]($style)"""

[custom.sw_version]
command = """ tail -n+2 "$INSTALL_SPACE_PATH/ref.txt" | head -n1 """
when = ''' test -f "$INSTALL_SPACE_PATH/ref.txt" '''
os = "linux"
style = "bg:green fg:black"
format = '[](fg:green)[${output}]($style)[](fg:green) '

[line_break]
disabled = false
