add_newline = false

# format = """
# $username\
# $hostname\
# $shlvl\
# $directory\
# $git_branch\
# $git_commit\
# $git_state\
# $git_status\
# $hg_branch\
# $memory_usage\
# $cmd_duration\
# $line_break\
# $jobs\
# $battery\
# $time\
# $status\
# $character"""

format = """
[┌───────────────────>](bold green)
[│](bold green)$username$hostname$directory$git_branch$git_commit$git_state$git_status$hg_branch$cmd_duration$jobs
[└─>](bold green)$status """

[time]
disabled = false
time_format = "%T"
format = "[$time]($style) "

[git_branch]
symbol = "g:"
format = "[$symbol$branch]($style)"

[directory]
truncate_to_repo = true
truncation_length = 5

[hostname]
format = "[$hostname]($style) "
style = "bold fg:242"

[username]
format = "[$user@]($style)"
style_user = "bold fg:242"

[status]
disabled = false

