prompt_order = [
    "username",
    "hostname",
    "directory",
    "git_branch",
    "git_commit",
    "git_state",
    "git_status",
    "hg_branch",
    "memory_usage",
    "cmd_duration",
    "jobs",
    "battery",
    "time",
    "character",
    ]

[git_branch]
symbol = ""
